### ISSUE TITLE
All-day events turn into 2am-2am events

### ISSUE THREAD

**Issue by vadim0x60** [MShekow/outlook-calendar-sync#2]
When I add an all-day event to one calendar, it gets copied into the other calendar shifted by 2 hours:

<img width="995" alt="Screenshot 2023-05-12 at 18 27 52" src="https://github.com/MShekow/outlook-calendar-sync/assets/3543310/ea9cc4f1-de79-48e6-a9a0-acf200344f0d">

The timezone of both calendars is the same, UTC+2. My guess is that the sync routine detects an all-day event in calendar A and inserts a 0:00 UTC - 0:00 UTC event into calendar B, which is not the same thing.

**Comment by MShekow** [comment]
Thanks for reporting this - I also noticed it myself. I'm currently working on a v0.5 version where this will be fixed, and where the synchronization becomes also a bit more stable (I'm having problems with SyncBlocker event _duplicates_).

The underlying cause is that the synchronization should also sync the value of the "is all day" attribute from the source event to the target sync-blocker event.

I'll close this ticket once v0.5 is released (expect 1-3 weeks).

**Comment by MShekow** [comment]
Fixed by releasing v0.5

**Comment by vadim0x60** [comment]
Thanks! This tool is a real life saver for me.
