### ISSUE TITLE
Location syncing as possible hex code

### ISSUE THREAD

**Issue by magnussi** [MShekow/outlook-calendar-sync#3]
All events are not syncing the correct location and instead are providing a long string that looks similar to a hex code:
e.g. 040000008200E00074C5B7101A82E00807E706132A9F178AE512D801000000000000000010000000CCB86D95BFE5FC4FB6A6FEB15169160A

**Comment by travisterrell** [comment]
IIRC, the PowerAutomate flow uses the location field for tracking purposes. If location is important to you, you can probably modify that to instead copy the existing Location values across and use another field for that purpose.

I haven't tried it, but from my memory of the script, there's no real reason it shouldn't work. (For privacy, I only wanted the times and busy status to be copied over, so this wasn't a problem for me.)

**Comment by MShekow** [comment]
Yes, @travisterrell  is right. The unique ID of the source event is used for correlating source even and blocker event, and it must be stored in _some_ field in the blocker event in the target calendar. I chose the _location_ field, because it seemed like the most suitable one to me - being the field where "data loss" (here: of the actual location) is causing the least amount of disturbance, IMO. You can feel free to change the sync algorithm to choose another field, but I guess you will only find the _body_ suitable. Maybe one of the _attendees_ fields work, but I have not checked.

**Comment by travisterrell** [comment]
@MShekow While you're here, I just want to issue my enormous thanks. I was really needing a solution that would play nicely with my consulting clients' Office365s and their various security policies. Without their admins' support, my best thought was going to be some sort of locally running agent, but I honestly didn't have time to research the API and write one anytime soon. Your PowerAutomate solution has worked so well. (And man... working in that UI is so rough. So seriously, thanks again!)

**Comment by MShekow** [comment]
@travisterrell you're welcome. 

I added a small note about the _location field_ containing a hexadecimal string to the blog post linked to by the README. This will hopefully avoid that future users stumble upon this issue again.
