### ISSUE TITLE
Canceled appointments

### ISSUE THREAD

**Issue by arcegabriel** [MShekow/outlook-calendar-sync#6]
I noticed that when I received a cancelled appointment on outlook "source" side, the meeting in outlook now says "Canceled: <rest of original title>"
However nothing gets reflected on the outlook "destination" side
How do I get those cancelations reflected? 
In case it matters, this is what I have for eventResponseTypes
[
  "organizer",
  "accepted",
  "tentativelyAccepted",
  "none",
  "notResponded"
]

**Comment by travisterrell** [comment]
I think you're seeing this because cancelled meetings are still meetings
for most intents and purposes. I'm sure you can track down a way to
identify the cancelled ones, though (if nothing else, could maybe look for
the text in the title?)

But I just wanted to mention that this feels like the correct behavior to
me, and share my personal solution. After I get the cancelled message, I
usually just hit the "remove from calendar" button that Outlook provides
for them, then it's no longer synced once it runs again. To my mind, if I'm leaving a
cancelled meeting on my calendar, it's because I want that time to remain
blocked, so still copying it between calendars is what I would want.

That said, since Outlook is able to recognize cancelled meetings, with some
digging you might be able to find the indicator it is using to recognize
them. (And then deal with the hell that is Power Automate's Edit UI, lol.)

**Comment by MShekow** [comment]
While it would be interesting to know what the `responseType` of cancelled meetings is, I also agree with @travisterrell in that this is expected behavior - thanks for your support / explanations.

**Comment by arcegabriel** [comment]
Thanks - I couldnt figure out the responsetype. Not sure where to look
For my use case - once something is cancelled it should be gone. I don't monitor the soure (secondary for me). The problem now is that even though the source is change to "Canceled: Title" the target is unchanged "<sync blocker> Title" 
So you can only see the event was cancelled on the source
Once I accept cancelation manually, it dissapears from source and target
Workarounds
1. Set outlook to accept all invites and delete cancelations. Problem I have is accept all invites
2. VBA to delete canceled meetings - I went this route
