### ISSUE TITLE
Check event count checks for exactly upper limit

### ISSUE THREAD

**Issue by pumpernickelBrad** [MShekow/outlook-calendar-sync#8]
When checking if the number of events in a calendar (1 or 2) I believe there's a logic error.
The check is looking for the number of events to be 'is equal to' the upper limit, which could fail to terminate if the number of events is greater than the upper limit.

I believe it should be 'is greater than' or 'is greater or equal'

![image](https://github.com/MShekow/outlook-calendar-sync/assets/30933286/e8bd97c0-f204-498f-9723-1ba01e973449)

**Comment by MShekow** [comment]
No, the _equals_ comparison is correct. The "Get calendar view of events cal1/2" action uses the `eventCountUpperLimit` variable for "Top count" (`eventCountUpperLimit` is defined in the block "Setting: Abort flow on too many events").

The "Check event count cal1" if-block (shown in your screenshot) essentially checks whether the "Get calendar view of events cal1/2" API limit has been reached, indicating that the API _could_ have returned even more events (within the _days to sync_ time period), and thus the flow should abort, because it causes unstable synchronization behavior.
